default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: WanderPal_development

test:
  <<: *default
  database: WanderPal_test
# production:
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
