default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: localhost

development:
  <<: *default
  database: WanderPal_development

test:
  <<: *default
  database: WanderPal_test
# production:
#   <<: *default
#   database: your_app_name_production
#   username: your_production_username
#   password: your_production_password
#   host: your_production_database_host
